LUT_VALUE = ['A', '2', '3', '4', '5', '6', '7', '8', '9', 'T', 'J', 'Q', 'K']
LUT_SUIT = ['c', 'd', 's', 'h']

NUM_VALUES = 13
NUM_SUITS = 4
NUM_CARDS_HAND = 5

NUM_MOVES = 4

HAND_RANK_ERROR = -1
HAND_RANK_HIGH_CARD = 0
HAND_RANK_PAIR = 1
HAND_RANK_TWO_PAIR = 2
HAND_RANK_THREE_OF_A_KIND = 3
HAND_RANK_STRAIGHT = 4
HAND_RANK_FLUSH = 5
HAND_RANK_FULL_HOUSE = 6
HAND_RANK_FOUR_OF_A_KIND = 7
HAND_RANK_STRAIGHT_FLUSH = 8

CARD_ERROR = -1
CARD_VALUE_ACE = 0
CARD_VALUE_TEN = 9
CARD_VALUE_JACK = 10
CARD_VALUE_QUEEN = 11
CARD_VALUE_KING = 12

TYPE_ERROR = -1
TYPE_SPADE = 0
TYPE_HEART = 1
TYPE_DIAMOND = 2
TYPE_CLUB = 3

MOVE_POWER_ERROR = -1
MOVE_ACCURACY_ERROR = -1
MOVE_SPECIAL_NONE = 0
