LUT_RANK = ['A', '2', '3', '4', '5', '6', '7', '8', '9', 'T', 'J', 'Q', 'K', 'E']
DICT_VALUE = {'2':2, '3':3, '4':4, '5':5, '6':6, '7':7, '8':8, '9':9, 'T':10, 'J':11, 'Q':12, 'K':13, 'A':14, 'E':0}
LUT_SUIT = ['c', 'd', 's', 'h', 'e']
LUT_HAND_RANK = ["HIGH CARD", "PAIR", "TWO PAIR", "THREE OF A KIND", "STRAIGHT", "FLUSH", "FULL HOUSE", "FOUR OF A KIND", "STRAIGHT FLUSH"]

NUM_VALUES = 13
NUM_SUITS = 4
NUM_CARDS_HAND = 5

NUM_MOVES = 4

HAND_RANK_ERROR = -1
HAND_RANK_HIGH_CARD = 0
HAND_RANK_PAIR = 1
HAND_RANK_TWO_PAIR = 2
HAND_RANK_THREE_OF_A_KIND = 3
HAND_RANK_STRAIGHT = 4
HAND_RANK_FLUSH = 5
HAND_RANK_FULL_HOUSE = 6
HAND_RANK_FOUR_OF_A_KIND = 7
HAND_RANK_STRAIGHT_FLUSH = 8
HAND_RANK_FIVE_OF_A_KIND = 9
HAND_RANK_FLUSH_HOUSE = 10
HAND_RANK_FLUSH_FIVE = 11

HAND_SAME_SUIT_BONUS = 2

CARD_RANK_ACE = 0
CARD_RANK_TEN = 9
CARD_RANK_JACK = 10
CARD_RANK_QUEEN = 11
CARD_RANK_KING = 12
CARD_RANK_ERROR = 13

CARD_SUIT_SPADE = 0
CARD_SUIT_HEART = 1
CARD_SUIT_DIAMOND = 2
CARD_SUIT_CLUB = 3
CARD_SUIT_ERROR = 4

TURN_UNDETERMINED = -1
TURN_PLAYER = 0
TURN_OPPONENT = 1

ACTION_ERROR = -1
ACTION_DRAW = 0
ACTION_CASHOUT = 1

MECHANIC_DRAW = 0
MECHANIC_FORCE_DRAW = 1
MECHANIC_LOCK = 2
MECHANIC_HOLD = 3

MULTIPLIER_HIGH_CARD_ATTACK = 1
MULTIPLIER_PAIR_ATTACK = 2
MULTIPLIER_TWO_PAIR_ATTACK = 1
MULTIPLIER_THREE_OF_A_KIND_ATTACK = 3
MULTIPLIER_STRAIGHT_ATTACK = 1
MULTIPLIER_FLUSH_ATTACK = 0
MULTIPLIER_FULL_HOUSE_ATTACK = 2
MULTIPLIER_FOUR_OF_A_KIND_ATTACK = 4
MULTIPLIER_STRAIGHT_FLUSH_ATTACK = 3
MULTIPLIER_FIVE_OF_A_KIND_ATTACK= 0
MULTIPLIER_FLUSH_HOUSE_ATTACK = 0
MULTIPLIER_FLUSH_FIVE_ATTACK = 0

MULTIPLIER_HIGH_CARD_HEALING = 0
MULTIPLIER_PAIR_HEALING = 0
MULTIPLIER_TWO_PAIR_HEALING = 2
MULTIPLIER_THREE_OF_A_KIND_HEALING = 0
MULTIPLIER_STRAIGHT_HEALING = 0
MULTIPLIER_FLUSH_HEALING = 1
MULTIPLIER_FULL_HOUSE_HEALING = 0
MULTIPLIER_FOUR_OF_A_KIND_HEALING = 0
MULTIPLIER_STRAIGHT_FLUSH_HEALING = 2
MULTIPLIER_FIVE_OF_A_KIND_HEALING= 0
MULTIPLIER_FLUSH_HOUSE_HEALING = 0
MULTIPLIER_FLUSH_FIVE_HEALING = 0

QUANTITY_HIGH_CARD_FORCE_DRAW_RANDOM = 0
QUANTITY_PAIR_FORCE_DRAW_RANDOM = 0
QUANTITY_TWO_PAIR_FORCE_DRAW_RANDOM = 0
QUANTITY_THREE_OF_A_KIND_FORCE_DRAW_RANDOM = 0
QUANTITY_STRAIGHT_FORCE_DRAW_RANDOM = 1
QUANTITY_FLUSH_FORCE_DRAW_RANDOM = 0
QUANTITY_FULL_HOUSE_FORCE_DRAW_RANDOM = 0
QUANTITY_FOUR_OF_A_KIND_FORCE_DRAW_RANDOM = 0
QUANTITY_STRAIGHT_FLUSH_FORCE_DRAW_RANDOM = 0
QUANTITY_FIVE_OF_A_KIND_FORCE_DRAW_RANDOM= 0
QUANTITY_FLUSH_HOUSE_FORCE_DRAW_RANDOM = 0
QUANTITY_FLUSH_FIVE_FORCE_DRAW_RANDOM = 0

QUANTITY_HIGH_CARD_FORCE_DRAW_TARGET = 0
QUANTITY_PAIR_FORCE_DRAW_TARGET = 0
QUANTITY_TWO_PAIR_FORCE_DRAW_TARGET = 0
QUANTITY_THREE_OF_A_KIND_FORCE_DRAW_TARGET = 0
QUANTITY_STRAIGHT_FORCE_DRAW_TARGET = 0
QUANTITY_FLUSH_FORCE_DRAW_TARGET = 0
QUANTITY_FULL_HOUSE_FORCE_DRAW_TARGET = 0
QUANTITY_FOUR_OF_A_KIND_FORCE_DRAW_TARGET = 0
QUANTITY_STRAIGHT_FLUSH_FORCE_DRAW_TARGET = 1
QUANTITY_FIVE_OF_A_KIND_FORCE_DRAW_TARGET= 0
QUANTITY_FLUSH_HOUSE_FORCE_DRAW_TARGET = 0
QUANTITY_FLUSH_FIVE_FORCE_DRAW_TARGET = 0

QUANTITY_HIGH_CARD_LOCK_RANDOM = 0
QUANTITY_PAIR_LOCK_RANDOM = 0
QUANTITY_TWO_PAIR_LOCK_RANDOM = 0
QUANTITY_THREE_OF_A_KIND_LOCK_RANDOM = 0
QUANTITY_STRAIGHT_LOCK_RANDOM = 0
QUANTITY_FLUSH_LOCK_RANDOM = 0
QUANTITY_FULL_HOUSE_LOCK_RANDOM = 0
QUANTITY_FOUR_OF_A_KIND_LOCK_RANDOM = 0
QUANTITY_STRAIGHT_FLUSH_LOCK_RANDOM = 0
QUANTITY_FIVE_OF_A_KIND_LOCK_RANDOM= 0
QUANTITY_FLUSH_HOUSE_LOCK_RANDOM = 0
QUANTITY_FLUSH_FIVE_LOCK_RANDOM = 0

QUANTITY_HIGH_CARD_LOCK_TARGET = 0
QUANTITY_PAIR_LOCK_TARGET = 0
QUANTITY_TWO_PAIR_LOCK_TARGET = 0
QUANTITY_THREE_OF_A_KIND_LOCK_TARGET = 0
QUANTITY_STRAIGHT_LOCK_TARGET = 0
QUANTITY_FLUSH_LOCK_TARGET = 1
QUANTITY_FULL_HOUSE_LOCK_TARGET = 0
QUANTITY_FOUR_OF_A_KIND_LOCK_TARGET = 0
QUANTITY_STRAIGHT_FLUSH_LOCK_TARGET = 1
QUANTITY_FIVE_OF_A_KIND_LOCK_TARGET= 0
QUANTITY_FLUSH_HOUSE_LOCK_TARGET = 0
QUANTITY_FLUSH_FIVE_LOCK_TARGET = 0

QUANTITY_HIGH_CARD_HOLD = 0
QUANTITY_PAIR_HOLD = 0
QUANTITY_TWO_PAIR_HOLD = 0
QUANTITY_THREE_OF_A_KIND_HOLD = 0
QUANTITY_STRAIGHT_HOLD = 0
QUANTITY_FLUSH_HOLD = 0
QUANTITY_FULL_HOUSE_HOLD = 1
QUANTITY_FOUR_OF_A_KIND_HOLD = 0
QUANTITY_STRAIGHT_FLUSH_HOLD = 0
QUANTITY_FIVE_OF_A_KIND_HOLD= 0
QUANTITY_FLUSH_HOUSE_HOLD = 0
QUANTITY_FLUSH_FIVE_HOLD = 0
