LUT_RANK = ['A', '2', '3', '4', '5', '6', '7', '8', '9', 'T', 'J', 'Q', 'K']
DICT_VALUE = {'2':2, '3':3, '4':4, '5':5, '6':6, '7':7, '8':8, '9':9, 'T':10, 'J':11, 'Q':12, 'K':13, 'A':14}
LUT_SUIT = ['c', 'd', 's', 'h']

NUM_VALUES = 13
NUM_SUITS = 4
NUM_CARDS_HAND = 5

NUM_MOVES = 4

HAND_RANK_ERROR = -1
HAND_RANK_HIGH_CARD = 0
HAND_RANK_PAIR = 1
HAND_RANK_TWO_PAIR = 2
HAND_RANK_THREE_OF_A_KIND = 3
HAND_RANK_STRAIGHT = 4
HAND_RANK_FLUSH = 5
HAND_RANK_FULL_HOUSE = 6
HAND_RANK_FOUR_OF_A_KIND = 7
HAND_RANK_STRAIGHT_FLUSH = 8
HAND_RANK_FIVE_OF_A_KIND = 9
HAND_RANK_FLUSH_HOUSE = 10
HAND_RANK_FLUSH_FIVE = 11

HAND_SAME_SUIT_BONUS = 2

CARD_ERROR = -1
CARD_VALUE_ACE = 0
CARD_VALUE_TEN = 9
CARD_VALUE_JACK = 10
CARD_VALUE_QUEEN = 11
CARD_VALUE_KING = 12

SUIT_ERROR = -1
SUIT_SPADE = 0
SUIT_HEART = 1
SUIT_DIAMOND = 2
SUIT_CLUB = 3

MOVE_POWER_ERROR = -1
MOVE_ACCURACY_ERROR = -1
MOVE_SPECIAL_NONE = 0

TURN_UNDETERMINED = -1
TURN_PLAYER = 0
TURN_OPPONENT = 1

ACTION_ERROR = -1
ACTION_DRAW = 0
ACTION_CASHOUT = 1
